name: Matrix from env

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  load_env:
    runs-on: ubuntu-latest
    outputs:
        SERVICE_NAME: "demo"
        SERVICE_HOOK_NAME: "demo-hook"
    steps:
      - name: Load Env variable
        run: |
          echo "NAME=service" >> $GITHUB_ENV
          echo "NAME_HOOK=service-hook" >> $GITHUB_ENV
      
      - name: Read Env Variable
        run: |
          echo "NAME=$NAME";
          echo "NAME_HOOK=$NAME_HOOK"
      
      - name: set output
        run: |
          echo "SERVICE_NAME=$NAME" >> $GITHUB_OUTPUT
          echo "SERVICE_HOOK_NAME=$NAME_HOOK" >> $GITHUB_OUTPUT

  read_output:
    needs: load_env
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        k8s_sa_name:
          - "${{ needs.load_env.outputs.SERVICE_NAME }}"
          - "${{ needs.load_env.outputs.SERVICE_HOOK_NAME }}"
    steps:
      - name: print sa for ${{ matrix.k8s_sa_name }}
        run: |
          echo ${{ matrix.k8s_sa_name }}

        
        
