name: Matrix from env

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  load_env:
    runs-on: ubuntu-latest
    outputs:
      SERVICE_NAME: ${{ steps.generate-output.outputs.SERVICE_NAME }}
      SERVICE_HOOK_NAME: ${{ steps.generate-output.outputs.SERVICE_HOOK_NAME }}
    steps:
      - name: Load Env variable
        run: |
          cat .env >> $GITHUB_ENV
      
      - name: Read Env Variable
        run: |
          echo "NAME=$SERVICE_NAME";
          echo "NAME_HOOK=${SERVICE_NAME}-hook"
      
      - name: generate-output
        id: generate-output
        run: |
          echo "SERVICE_NAME=$SERVICE_NAME" >> $GITHUB_OUTPUT
          echo "SERVICE_HOOK_NAME=${SERVICE_NAME}-hook" >> $GITHUB_OUTPUT

  read_output:
    needs: load_env
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        k8s_sa_name:
          - "${{ needs.load_env.outputs.SERVICE_NAME }}"
          - "${{ needs.load_env.outputs.SERVICE_HOOK_NAME }}"
    steps:
      - name: print sa for ${{ matrix.k8s_sa_name }}
        run: |
          echo ${{ matrix.k8s_sa_name }}

        
        
